// src/lib/components/Experience.svelte
<script lang="ts">
	import Text from './Text.svelte';

	export let id: string;
	export let date: {start: string; end: string};
	export let title: string;
	export let link: string | undefined;
</script>

<section {id}>
	<Text kind="h3">
		{title}{#if link} <a rel="noopener noreferrer" target="_blank" href={link}>(link)</a>{/if}
	</Text>
	<Text kind="p">
		{date.start} - {date.end}
	</Text>
	<Text kind="p"><slot /></Text>
</section>

<style lang="scss">
	section {
		margin-top: 1em;
	}

	a {
		transition: opacity 150ms ease;

		font-weight: 200;

		color: var(--color-text-muted);
		margin: {
			left: 0.5rem;
		}
		opacity: 0;

		section:hover & {
			opacity: initial;
		}
	}
</style>

// app/components/experience.tsx
import type { PropsWithChildren } from 'react';

type Props = PropsWithChildren<{
	id: string;
	title: string;
	role: string;
	link: {
		href: string;
		display: React.ReactNode;
	};
	date: {
		start: string;
		end: string;
	};
}>;

export function Experience({ id, title, children, date, link, role }: Props) {
	return (
		<div id={id}>
			<div className='w-full flex justify-between items-baseline dark:text-pink-500'>
				<h3 className='text-2xl font-medium'>{title}</h3>
				<a href={link.href} target='_blank' rel='noreferrer noopener' className='text-xl font-light underline'>
					{link.display}
				</a>
			</div>
			<div className='w-full flex justify-between mb-2'>
				<p>{role}</p>
				<p>
					{date.start} - {date.end}
				</p>
			</div>

			<p>{children}</p>
		</div>
	);
}
