// src/routes/404.svelte
<script lang="ts">
	import Button from '$lib/components/Button.svelte';
	import ButtonGroup from '$lib/components/ButtonGroup.svelte';

	import Container from '$lib/components/Container.svelte';
	import Header from '$lib/components/Header.svelte';
	import PageSeo from '$lib/components/PageSeo.svelte';
	import Text from '$lib/components/Text.svelte';
	import {header} from '$lib/config/page-header';
</script>

<Container main id="main">
	<Header {...header} />

	<PageSeo pageTitle="404" />

	<main id="links">
		<Text kind="h3" animation="fade">Page not found</Text>
		<ButtonGroup>
			<Button href="/" sequentialFade={0}>Home</Button>
		</ButtonGroup>
	</main>
</Container>

// src/pages/404.tsx
import clsx from 'clsx';
import {NextSeo} from 'next-seo';
import Link from 'next/link';
import {FC} from 'react';
import Button from '../components/button';
import styles from '../components/button-group.module.scss';
import Container from '../components/container';
import Header from '../components/header';
import Text from '../components/text';
import {header} from '../config';

const NotFound: FC = () => (
	<>
		<NextSeo title='404' openGraph={{title: '404'}} />

		<Container main>
			<Header {...header} />

			<main id='links'>
				<Text kind='h3' animation='fade'>
					Page not found
				</Text>
				<div className={clsx(styles['button-group'], styles.animated)}>
					<Link passHref href='/'>
						<Button href='/'>Home</Button>
					</Link>
				</div>
			</main>
		</Container>
	</>
);

export default NotFound;
