// src/lib/components/Header.svelte
<script lang="ts">
	import Text from './Text.svelte';

	export let title: string | undefined;
	export let subtitle: string | undefined;
</script>

<header id="header">
	<Text kind="h1" animation="underline">{title}</Text>
	<Text kind="h2" as="p" animation="fade">{subtitle}</Text>
</header>

<style lang="scss">
	header {
		margin-bottom: 3em;
	}
</style>

// src/components/header.tsx
import {FC} from 'react';
import Text from './text';
import styles from './header.module.scss';

export interface Props {
	title?: string;
	subtitle?: string;
}

const Header: FC<Props> = props => (
	<header id='header' className={styles.header}>
		{props.title && (
			<Text kind='h1' animation='underline'>
				{props.title}
			</Text>
		)}
		{props.subtitle && (
			<Text kind='h2' as='p' animation='fade'>
				{props.subtitle}
			</Text>
		)}
	</header>
);

export default Header;
